/* M2 — Multiple-choice bank (Paper 01 style). ans = index of the correct option. */
const MCQ = [
  { q: 'Which of the following is a vector quantity?', o: ['kinetic energy', 'power', 'impulse', 'pressure'], ans: 2,
    why: 'Impulse = force × time = change in momentum, so it has direction. Energy, power and pressure are scalars.' },
  { q: 'Two forces of 5 N and 12 N act at a point. Which of these <strong>cannot</strong> be their resultant?', o: ['7 N', '13 N', '17 N', '18 N'], ans: 3,
    why: 'The resultant lies between |12 − 5| = 7 N and 12 + 5 = 17 N. 18 N is outside the range.' },
  { q: 'A walker moves 6 km north then 8 km east. Her resultant displacement is', o: ['10 km on a bearing of 053°', '10 km on a bearing of 037°', '14 km on a bearing of 053°', '2 km on a bearing of 090°'], ans: 0,
    why: '\\(\\sqrt{6^2 + 8^2} = 10\\) km; bearing \\(= \\tan^{-1}(8/6) = 53.1^\\circ\\) east of north. 14 km is the distance, not the displacement.' },
  { q: 'A force of 20 N acts at 30° above the horizontal. Its vertical component is', o: ['10 N', '17.3 N', '20 N', '11.5 N'], ans: 0,
    why: '\\(20\\sin30^\\circ = 10\\) N. 17.3 N is the horizontal component.' },
  { q: 'A 2.0 kg block rests on a smooth slope inclined at 30°. The component of its weight down the slope is (\\(g = 9.81\\ \\text{m s}^{-2}\\))', o: ['9.81 N', '17.0 N', '19.6 N', '11.3 N'], ans: 0,
    why: '\\(mg\\sin30^\\circ = 19.62 \\times 0.5 = 9.81\\) N. 17.0 N is \\(mg\\cos30^\\circ\\) — the classic trap.' },
  { q: 'A vector has components \\((3,\\ -4,\\ 12)\\). Its magnitude is', o: ['11', '13', '19', '169'], ans: 1,
    why: '\\(\\sqrt{9 + 16 + 144} = \\sqrt{169} = 13\\). 11 comes from adding components; 169 forgets the square root.' },
  { q: '\\(\\vec{a} = (2,\\ -1,\\ 3)\\) and \\(\\vec{b} = (1,\\ 4,\\ k)\\) are perpendicular when \\(k\\) equals', o: ['\\(-\\tfrac23\\)', '\\(\\tfrac23\\)', '2', '−2'], ans: 1,
    why: '\\(\\vec{a}\\cdot\\vec{b} = 2 - 4 + 3k = 0\\) → \\(k = \\tfrac23\\).' },
  { q: 'A force acts along \\(+x\\) at a point displaced along \\(+y\\) from a pivot. Using \\(\\vec{\\tau} = \\vec{r}\\times\\vec{F}\\) and the right-hand rule, the torque points along', o: ['\\(+z\\)', '\\(-z\\)', '\\(+x\\)', 'nowhere — it is zero'], ans: 1,
    why: 'Fingers along \\(\\vec{r}\\) (\\(+y\\)), curl towards \\(\\vec{F}\\) (\\(+x\\)): the thumb points along \\(-z\\) (a clockwise moment seen from above).' },
  { q: 'A ball\'s velocity changes from 4.0 m s⁻¹ east to 3.0 m s⁻¹ north. The magnitude of the change in velocity is', o: ['1.0 m s⁻¹', '5.0 m s⁻¹', '7.0 m s⁻¹', 'zero'], ans: 1,
    why: '\\(\\Delta\\vec{v} = \\vec{v} - \\vec{u}\\): 3 north + 4 west, magnitude \\(\\sqrt{9 + 16} = 5.0\\) m s⁻¹. 1.0 is the change in <em>speed</em>.' },
  { q: 'Two forces, each of magnitude \\(F\\), act at 120° to each other. The magnitude of their resultant is', o: ['0', '\\(F\\)', '\\(\\sqrt3\\,F\\)', '\\(2F\\)'], ans: 1,
    why: '\\(R = 2F\\cos(120^\\circ/2) = 2F\\cos60^\\circ = F\\).' },
  { q: 'A force with components \\((3,\\ -2)\\) N moves its point of application through a displacement with components \\((4,\\ 6)\\) m. The work done is', o: ['0 J', '24 J', '12 J', '−12 J'], ans: 0,
    why: '\\(W = F_xs_x + F_ys_y = 12 - 12 = 0\\): the force is perpendicular to the displacement.' },
  { q: 'A vector of magnitude 1 in the same direction as \\((6,\\ 8)\\) is', o: ['\\((0.6,\\ 0.8)\\)', '\\(\\tfrac{1}{14}(6,\\ 8)\\)', '\\((0.8,\\ 0.6)\\)', '\\((3,\\ 4)\\)'], ans: 0,
    why: 'Divide each component by the magnitude 10, not by the sum of components (14).' },
  { q: 'Rain falls vertically at 6.0 m s⁻¹. To a cyclist moving at 8.0 m s⁻¹ the rain appears to move at', o: ['2.0 m s⁻¹', '10 m s⁻¹', '14 m s⁻¹', '6.0 m s⁻¹'], ans: 1,
    why: '\\(\\vec{v}_{\\text{rain}} - \\vec{v}_{\\text{cyclist}}\\) has magnitude \\(\\sqrt{36 + 64} = 10\\) m s⁻¹.' },
  { q: 'A picture of weight 10 N hangs from two strings, each at 30° to the horizontal. The tension in each string is', o: ['5.0 N', '10 N', '20 N', '11.5 N'], ans: 1,
    why: '\\(2T\\sin30^\\circ = 10\\) → \\(T = 10\\) N.' },
  { q: 'Two forces of 10 N have a resultant of 14.1 N. The angle between them is', o: ['45°', '60°', '90°', '120°'], ans: 2,
    why: '\\(14.1 = 2(10)\\cos(\\theta/2)\\) → \\(\\cos(\\theta/2) = 0.705\\) → \\(\\theta = 90^\\circ\\) (\\(10\\sqrt2 = 14.1\\)).' },
  { q: 'A triangle has two perpendicular sides of length 2 m and 3 m meeting at a vertex. Using \\(\\tfrac12|\\vec{a}\\times\\vec{b}|\\), its area is', o: ['6 m²', '3 m²', '5 m²', '1.5 m²'], ans: 1,
    why: '\\(\\tfrac12 ab\\sin90^\\circ = \\tfrac12(2)(3) = 3\\) m².' },
  { q: 'A force of 10 N acts at 60° to a displacement of 5 m. The work done \\(W = \\vec{F}\\cdot\\vec{s}\\) is', o: ['25 J', '43.3 J', '50 J', '0 J'], ans: 0,
    why: '\\(W = Fs\\cos\\theta = 10 \\times 5 \\times \\cos60^\\circ = 25\\) J. 43.3 J wrongly uses sin.' },
  { q: 'The angle between the vectors \\((1,\\ 1,\\ 0)\\) and \\((1,\\ 0,\\ 1)\\) is', o: ['30°', '45°', '60°', '90°'], ans: 2,
    why: '\\(\\cos\\theta = \\dfrac{1}{\\sqrt2\\sqrt2} = \\tfrac12\\) → \\(60^\\circ\\).' },
  { q: 'A boat heads straight across a river at 4.0 m s⁻¹ relative to the water; the current is 3.0 m s⁻¹. Its speed relative to the bank is', o: ['1.0 m s⁻¹', '5.0 m s⁻¹', '7.0 m s⁻¹', '4.0 m s⁻¹'], ans: 1,
    why: 'The two velocities are perpendicular: \\(\\sqrt{16 + 9} = 5.0\\) m s⁻¹.' },
  { q: 'A vector has components \\((-5,\\ 5\\sqrt3)\\). The angle it makes with the \\(+x\\) axis, measured anticlockwise, is', o: ['60°', '120°', '150°', '300°'], ans: 1,
    why: 'Acute angle \\(\\tan^{-1}(\\sqrt3) = 60^\\circ\\); second quadrant → \\(180 - 60 = 120^\\circ\\). The calculator alone gives −60° — sketch the quadrant!' },
  { q: 'Which statement is <strong>false</strong> for all non-zero, non-parallel vectors?', o: ['\\(\\vec{a}\\cdot\\vec{b} = \\vec{b}\\cdot\\vec{a}\\)', '\\(\\vec{a}\\times\\vec{b} = \\vec{b}\\times\\vec{a}\\)', '\\(\\vec{a}\\times\\vec{a} = \\vec{0}\\)', '\\(\\vec{a}\\cdot\\vec{a} = |\\vec{a}|^2\\)'], ans: 1,
    why: 'The cross product is anti-commutative: \\(\\vec{b}\\times\\vec{a} = -\\vec{a}\\times\\vec{b}\\).' },
  { q: 'At the highest point of a projectile\'s path (no air resistance)', o: ['velocity and acceleration are both zero', 'velocity is horizontal and acceleration is vertically downwards', 'velocity is zero and acceleration is downwards', 'velocity and acceleration are both horizontal'], ans: 1,
    why: 'Only the vertical component of velocity is zero at the top; acceleration is \\(g\\) downwards throughout.' },
  { q: 'A charged particle moves parallel to a uniform magnetic field. The magnetic force on it is', o: ['maximum', 'zero', '\\(qvB\\)', 'along the field'], ans: 1,
    why: '\\(|q\\vec{v}\\times\\vec{B}| = qvB\\sin0^\\circ = 0\\).' },
  { q: 'The lines \\(\\vec{r} = (1, 2, 3) + \\lambda(2, -1, 1)\\) and \\(\\vec{r} = (0, 1, 0) + \\mu(-4, 2, -2)\\) are', o: ['intersecting', 'parallel and distinct', 'skew', 'the same line'], ans: 1,
    why: '\\((-4, 2, -2) = -2(2, -1, 1)\\) so they are parallel. \\((0,1,0) - (1,2,3) = (-1,-1,-3)\\) is not a multiple of \\((2,-1,1)\\), so they are distinct.' },
  { q: 'The distance from \\((1, 1, 1)\\) to the plane \\(2x + y - 2z = 4\\) is', o: ['1', '3', '\\(\\tfrac13\\)', '\\(\\tfrac53\\)'], ans: 0,
    why: '\\(\\dfrac{|2 + 1 - 2 - 4|}{\\sqrt{4 + 1 + 4}} = \\dfrac{3}{3} = 1\\).' },
  { q: 'Forces of 3 N, 4 N and 5 N act at a point in equilibrium. The angle between the 3 N and 4 N forces is', o: ['90°', '37°', '53°', '143°'], ans: 0,
    why: 'The 3 N and 4 N forces must have a resultant of 5 N; since \\(3^2 + 4^2 = 5^2\\) they are at 90°.' },
  { q: 'A force of 50 N acts at the end of a 0.20 m spanner at 30° to the spanner. The torque is', o: ['5.0 N m', '8.7 N m', '10 N m', '2.5 N m'], ans: 0,
    why: '\\(\\tau = rF\\sin\\theta = 0.20 \\times 50 \\times \\sin30^\\circ = 5.0\\) N m.' },
  { q: 'The component of the vector \\((3,\\ 4)\\) in the direction of \\((1,\\ 1)\\) (i.e. at 45° to the \\(x\\)-axis) is', o: ['7', '4.95', '3.5', '5'], ans: 1,
    why: '\\(3\\cos45^\\circ + 4\\sin45^\\circ = \\dfrac{7}{\\sqrt2} = 4.95\\).' },
  { q: 'An aircraft heads due north. A wind blows from the east. Relative to the ground the aircraft travels', o: ['west of north', 'east of north', 'due north', 'due west'], ans: 0,
    why: 'A wind <em>from</em> the east pushes the aircraft westwards, so its track is west of north.' },
  { q: 'If \\(|\\vec{a} + \\vec{b}| = |\\vec{a} - \\vec{b}|\\) for non-zero vectors, then', o: ['\\(\\vec{a}\\parallel\\vec{b}\\)', '\\(\\vec{a}\\perp\\vec{b}\\)', '\\(|\\vec{a}| = |\\vec{b}|\\)', '\\(\\vec{a} = \\vec{b}\\)'], ans: 1,
    why: 'Squaring: \\(a^2 + 2\\vec{a}\\cdot\\vec{b} + b^2 = a^2 - 2\\vec{a}\\cdot\\vec{b} + b^2\\) → \\(\\vec{a}\\cdot\\vec{b} = 0\\). (The diagonals of a rectangle are equal.)' }
];
